### ISSUE TITLE
Path for js files not correct in index.html

### ISSUE THREAD

**Issue by arvindkalra** [coding-blocks/codingblocks.com#145]
i just started working on this project but the index.html page has some issues.
![webstorm1](https://user-images.githubusercontent.com/29686907/27746571-62d4453e-5de5-11e7-843e-e9000c815be2.png)
the path for the js files seems to be wrong as when the js files are given the path with / (slash in the beginning) the browser shows 404 error.
But,
![webstorm2](https://user-images.githubusercontent.com/29686907/27746658-b4e99cc0-5de5-11e7-97c8-c0d9bdcf6e07.png)
If I remove all the (slashes in the beginning) the index.html page starts to work fine. And those errors are removed.
Later the same issue arises for the CSS files..

I think the index.html and the JS folder are present in the same folder so what is the need of (slash in the begining)....

BEFORE
![before](https://user-images.githubusercontent.com/29686907/27746829-5c2c3d08-5de6-11e7-8f2c-4a3c39fbca19.png)

AFTER
![after](https://user-images.githubusercontent.com/29686907/27746832-61adbcd4-5de6-11e7-84a2-15dda4a818c8.png)

**Comment by championswimmer** [comment]
you need to use gulp to build and then serve from that folder

**Comment by witty123** [comment]
Outdated issue.
