### ISSUE TITLE
Loading Animation

### ISSUE THREAD

**Issue by AshishkrGoyal** [coding-blocks/codingblocks.com#183]
![screenshot 9](https://user-images.githubusercontent.com/25322851/29059554-beab46f2-7c33-11e7-82db-f04eb453f90a.png)
During loading of web page image is not showing while other content is visible. by adding preloader we can avoid this.

**Comment by championswimmer** [comment]
You want to work on it ?

**Comment by AshishkrGoyal** [comment]
@championswimmer yes sir..
i will solve it..Thanks Sir 😄

**Comment by hereisnaman** [comment]
@AshishkrGoyal you can add the script to scripts partial which gets add up on every page.
