### ISSUE TITLE
Rupee Sign Not Visible in Windows 7 

### ISSUE THREAD

**Issue by flaredragon** [coding-blocks/codingblocks.com#285]
A Windows 7 only issue The Rupee Sign with course price is not identified by any browser.
Can be corrected by adding the 
![capturse](https://user-images.githubusercontent.com/29121452/33514414-a2d7cc42-d779-11e7-93a4-59101196fab6.PNG)
[Hind Google Font](https://fonts.google.com/specimen/Hind?selection.family=Hind)

**Comment by championswimmer** [comment]
@flaredragon please add the font. or if possible @hereisnaman please do it
