### ISSUE TITLE
[Bug]Broken Links in Footer

### ISSUE THREAD

**Issue by shreyateeza** [coding-blocks/codingblocks.com#441]
## Description
The highlighted links are either broken or point to another link.
![cbfooter](https://user-images.githubusercontent.com/30488330/40043982-b46fd0b2-5843-11e8-86a5-3b2a076c408c.PNG)

## Required
[ ] Replace the broken link with another link to a post from the [FB page of Coding Blocks](https://www.facebook.com/codingblocksindia/). [For Twitter Feed]
[ ] Replace the broken links to appropriate ones. [For rest]

Filed the bug as mentioned in #29 .
@championswimmer Please approve this issue!

**Comment by frunkad** [comment]
https://github.com/coding-blocks/codingblocks.com/pull/459

I couldn't find the appropriate fb.me link so I created a bit.ly link as it seem odd to have one bit.ly and two fb.me
