### ISSUE TITLE
In mobile view (iOS), texts below FAQ seem out of structure

### ISSUE THREAD

**Issue by reshusinghhh** [coding-blocks/codingblocks.com#451]
![whatsapp image 2018-05-20 at 2 46 21 am 1](https://user-images.githubusercontent.com/18489140/40273150-a7015d90-5bd8-11e8-839a-adb3c0460dcb.jpeg)

**Comment by championswimmer** [comment]
What is wrong ?

**Comment by reshusinghhh** [comment]
text layout looks wrong, if that counts! :)

**Comment by championswimmer** [comment]
What layout would you suggest correct? 🤣 
It is a sentence too long to be written in one line, so it is wrapped.

**Comment by reshusinghhh** [comment]
ok ok not so valid issue :)
