### ISSUE TITLE
links on https://codingblocks.com/resources broken

### ISSUE THREAD

**Issue by shreyjain711** [coding-blocks/codingblocks.com#475]
In reference to issue #29  (find a bug / suggest a feature)

the section titles, e.g. competitive.coding, javascript, talks and conferences.
All the section headers which are linking to  '/category/#<section-header>', 
/category is not present thus the 404 page appears

**Comment by shreyjain711** [comment]
@championswimmer please set the bounty points for this bug. I have made the pull request, so wanted to claim the points for it as well 😄

**Comment by championswimmer** [comment]
done
