### ISSUE TITLE
Overlapping of Content

### ISSUE THREAD

**Issue by kunalvishnoi** [coding-blocks/codingblocks.com#511]
In about Us Reviews Page https://codingblocks.com/reviews/
there is a overlapping of name and content in Mobile View
![issue2](https://user-images.githubusercontent.com/24695316/42063147-fad689b0-7b4d-11e8-8e47-9ab7f82cb429.png)
I want to take up the issue
with reference to #29

**Comment by architkshk** [comment]
@witty123 resolved this issue in https://github.com/coding-blocks/codingblocks.com/pull/515 .

**Comment by viditvarshney** [comment]
@kunalvishnoi  if issue is solved then close the issue
