### ISSUE TITLE
In some Pages headers links are not working

### ISSUE THREAD

**Issue by kunalvishnoi** [coding-blocks/codingblocks.com#512]
In classroom programs C++ couse page https://codingblocks.com/classroom-courses/c-plus-plus-for-beginners.html
The three links in headers i.e Highlights/ contents/ FAQ 
On clicking the Contents it is not redirecting anywhere but Highlights and FAQ are working fine this is due to mismatching of Id name in href of contents and destination id name.

I would like to take up the issue.
with reference to #29

**Comment by kunalvishnoi** [comment]
Same problem in the  JAVA course page https://codingblocks.com/classroom-courses/java-for-beginners.html
Content link is not working

**Comment by witty123** [comment]
Please see the already opened issues with respect to the one you are submitting.
