### ISSUE TITLE
Navbar on Scroll

### ISSUE THREAD

**Issue by kunalvishnoi** [coding-blocks/codingblocks.com#513]
Its my suggestion as all the pages are too scrollable and if a person wants from middle to change the page for that he wants to go to again the top of the page to choose from navbar
Instead of Navbar only shows on top, if a user backscroll from any instance the navbar should appear.
i.e the navbar will be visible again if someone scroll Up.
with reference to #29

**Comment by VibhorCodecianGupta** [comment]
@witty123 Isn't the navbar already sticky?
