### ISSUE TITLE
content trimmed

### ISSUE THREAD

**Issue by pg07codes** [coding-blocks/codingblocks.com#535]
![x](https://user-images.githubusercontent.com/34238240/42703901-910e1594-86eb-11e8-9ede-d3b0579780c7.JPG)

the information part is trimmed at the sides of right most cards.

**Comment by rakshitkumarcse** [comment]
@witty123 @abhishek97 Is this issue still open?

**Comment by shubhamofbce** [comment]
is this issue still open?? I want to work on this.
