### ISSUE TITLE
convert map addresses to latitude, longitude 

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/codingblocks.com#552]
as visitors increased, we are hitting geocoding free tier limit. 

no problem - let's use hardcoded lat/lng markers.

**Comment by architkshk** [comment]
@championswimmer have you enabled billing on the account to enable $200 free monthly credit?

**Comment by Dhroov7** [comment]
@championswimmer Done. PR #554

**Comment by firefinchdev** [comment]
@championswimmer 
Done #555 
Pls Review.
