### ISSUE TITLE
Redirect online courses to online CB

### ISSUE THREAD

**Issue by witty123** [coding-blocks/codingblocks.com#566]
- [ ] Online courses tab should open online.codingblocks.com in a new window, similarly the dropdown links for online courses tab should direct user to specific courses on online codingblocks
<img width="1114" alt="screen shot 2018-08-13 at 1 38 45 pm" src="https://user-images.githubusercontent.com/7976098/44020059-4b5c2a4c-9efe-11e8-90b5-271467274864.png">

- [ ] Register button should direct to online codingblocks courses page
<img width="1440" alt="screen shot 2018-08-13 at 1 39 36 pm" src="https://user-images.githubusercontent.com/7976098/44020087-5c1f9436-9efe-11e8-8811-b48fd2e52574.png">

**Comment by VibhorCodecianGupta** [comment]
#566, already done earlier.

**Comment by architkshk** [comment]
@witty123 "try for free" redirects to online codingblocs courses page. maybe i should change register now to online course's page and replace "try for free" with "details"

**Comment by witty123** [comment]
@architkshk both should redirect to that page only

**Comment by VibhorCodecianGupta** [comment]
@witty123 
There is a C++ (DS & Algo) course in codingblocks.com. However, there are two courses in online.codingblocks.com, Launchpad and Algo++. What I've done is, I've added a course called C++ Advanced (DS & ALgo) in the online courses tab which redirects to Algo++ and a course C++ Foundation (with DS & Algo) which redirects to Launchpad. Works?

**Comment by architkshk** [comment]
@witty123 Done #568
