### ISSUE TITLE
Add banner at the bottom of every classroom course

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.com#590]
Hi @VibhorCodecianGupta can you please look into this. 
![whatsapp image 2018-11-11 at 1 37 59 pm](https://user-images.githubusercontent.com/8109774/48310589-9b2d1900-e5b7-11e8-91ed-a8fc30c7885e.jpeg)

**Comment by abhishek97** [comment]
@VibhorCodecianGupta

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 will do. Is the design already available or do I have to design one?

**Comment by witty123** [comment]
@VibhorCodecianGupta You've to add the banner of "Get free access to online course"(the one in red) in every classroom course page. Design will be same as shared in the description.

**Comment by witty123** [comment]
Closed in #593
