### ISSUE TITLE
Adding package-lock.json to gitignore

### ISSUE THREAD

**Issue by muskankhedia** [coding-blocks/codingblocks.com#660]
As the package-lock.json gets modified on every npm install and create problems for the contributors if pushed by mistake in any of the pull requests. So instead of keeping a check on every pull request, it is better to add it in the .gitignore file so it won't create disturbances anymore.

**Comment by muskankhedia** [comment]
@witty123 Can I add this?

**Comment by abhishek97** [comment]
You should never ignore lock files. They are meant to committed to the repo, as they are required to reproduce exact dependencies. Ignoring lock files defeats their purpose. I encourage you to read about why we need lock files and how do they work

**Comment by muskankhedia** [comment]
Thank you. I have checked for it and now well aware of the advantages and disadvantages of committing a package-lock.json file, and however, its advantages have more worth than the disadvantages.
