### ISSUE TITLE
FAQ button on Angular Bootcamp page is broken

### ISSUE THREAD

**Issue by daniloff200** [coding-blocks/codingblocks.com#769]
On https://codingblocks.com/bootcamps/angular.html page we have FAQ button, but, it doesn't work, because there's no FAQ section on this page

![Selection_031](https://user-images.githubusercontent.com/13692220/66706431-07217f80-ed3b-11e9-94cd-0f12efec10d1.png)

My solution is to remove FAQ button, if we don't have questions

OR

Can somebody share these questions here, and I can add them

**Comment by may55** [comment]
Can I work on this issue?

**Comment by daniloff200** [comment]
Nobody cares about that
