### ISSUE TITLE
Link to one of the photos on review page is broken

### ISSUE THREAD

**Issue by daniloff200** [coding-blocks/codingblocks.com#774]
On https://codingblocks.com/classroom-courses/advanced-data-structures-and-algorithms-for-interviews.html photo of DHRUV KULSHRESHTHA is 53.jpg, which actually doesn't exist, and was deleted in #710 , maybe, accidentally

Gonna go down to commits before, and return the image back

**Comment by daniloff200** [comment]
lol, @VIshal1003, nice code stealing

Just copy my PR, ahahah,  please, don't tell, that you have not seen my PR above

**Comment by Vishal1003** [comment]
@daniloff200 I really didn't saw your pr. If I would have seen it before I'd have never made a pr. I'm a beginner. I saw this issue open and so I contributed to this (I was unaware that it was fixed by you before) I'm sorry for my fault.

**Comment by daniloff200** [comment]
Nobody cares about that
