### ISSUE TITLE
Logos are not visible at Success Stories page

### ISSUE THREAD

**Issue by daniloff200** [coding-blocks/codingblocks.com#775]
On https://codingblocks.com/success-stories/ bunch of logos a broken. Here's the examples (that's not all)

![Selection_032](https://user-images.githubusercontent.com/13692220/66709055-c9d1e780-ed64-11e9-982e-9cbfde842792.png)
![Selection_033](https://user-images.githubusercontent.com/13692220/66709056-cb9bab00-ed64-11e9-9387-00bd0b5bb613.png)
![Selection_034](https://user-images.githubusercontent.com/13692220/66709057-cd656e80-ed64-11e9-82ad-47fd41613896.png)

**Comment by daniloff200** [comment]
There are various companies with that, but, the most popular is Adobe. Adobe.com is not available on Clearbit

**Comment by kcclemo** [comment]
The URLs are populated from here:
https://app.codingblocks.com/public_stories

But, that data does not appear to be on Github.

**Comment by Andre-rsfc** [comment]
I will work on it

**Comment by Andre-rsfc** [comment]
😄

**Comment by Andre-rsfc** [comment]
The API `https://app.codingblocks.com/public_stories` Is blocked by cors :/, but the change to not break the image is use `onerror`in html tag.

**Comment by daniloff200** [comment]
Nobody cares about that
