### ISSUE TITLE
<img> tag is self closing

### ISSUE THREAD

**Issue by JohJohan** [coding-blocks/codingblocks.com#807]
The image tag is self closing see as it cannot have child nodes.

More info see:
https://stackoverflow.com/questions/23890716/why-is-the-img-tag-not-closed-in-html/23890817

**Comment by JohJohan** [comment]
See https://github.com/coding-blocks/codingblocks.com/pull/808

**Comment by subodhk01** [comment]
What exactly are you trying to say here??

**Comment by JohJohan** [comment]
```<img>``` tag doesn't have to be closed see stackoverflow link and my pull request for the fixes.

**Comment by subodhk01** [comment]
It doesn't matter if you use /> or not

**Comment by JohJohan** [comment]
Okay then i close this ticket
